baseURL = "https://fenghuanghsin.github.io/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = "星空下微風輕拂黃光閃耀的世界"
theme = "PaperMod"
enableRobotsTXT = true
hasCJKLanguage = true
enableGitInfo = true
[params]
ShowWordCount = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowRssButtonInSectionTermList = true 
[params.homeInfoParams]
Title = "2025年至2038年紀錄"
Content = "高考三級資訊處理榜首"
[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/fenghuanghsin"
[params.assets]
disableFingerprinting = true
[params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
[params.search]
enable = true
searchEngine = "fuse"
[outputs]
home = ["HTML", "RSS", "JSON"]
[menu]
  [[menu.main]]
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "文章列表"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    name = "搜尋"
    url = "/search/"
    weight = 3

  [[menu.main]]
    name = "分類"
    url = "/categories/"
    weight = 4

  [[menu.main]]
    name = "標籤"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    name = "關於"
    url = "/about/"
    weight = 6
